### ISSUE TITLE
modify create_observation_model so it can take in single distributions w/o using `expand_constant_value`

### ISSUE THREAD

**Issue by smwindecker** [idem-lab/lowerGPreff#10]
Currently `create_observation_model` requires the proportion and delay objects to be in full expanded version (unique value for each jurisdiction x date pair). this is clunky for times when you do not have time-varying for these. 

So should be able to turn into matrix form inside the function with single input not only expanded long input.

**Comment by smwindecker** [comment]
discussed with Nick 19/2 and he think it would be good to have the `create_observation_model` take in the expanded data structure as default instead of having an option you need to specify for timevarying or not. 

the user shouldn't have to make the expanded version, though. rather, it gets made for them as part of creating the delay dist object.

**Comment by AugustHao** [comment]
agreed, and this also means creating a time-varying delay superclass is extra helpful as a quick overview for telling apart the single time point version from the time varying one
