### ISSUE TITLE
Combine function masked by dplyr::combine

### ISSUE THREAD

**Issue by SeniorKate** [idem-lab/lowerGPreff#18]
```
Attaching package: ‘dplyr’

The following object is masked from ‘package:lowerGPreff’:

    combine
```

Nick T suggestions: 
- https://stackoverflow.com/questions/18513607/how-to-extend-s3-method-from-another-package-without-loading-the-package/72772582#72772582
- s3 methods chapter of Advanced R

**Comment by njtierney** [comment]
https://github.com/njtierney/democombine

**Comment by SeniorKate** [comment]
Changed to 'add'
